#!/usr/bin/env ruby

######
# Run irb for interactive fiddling with this library from the source.

require 'rubygems'
$LOAD_PATH << File.expand_path('../lib', __FILE__)

require 'ncs_navigator/mdes'
ENV[NcsNavigator::Mdes::SourceDocuments::BASE_ENV_VAR] ||=
  File.expand_path('../spec/doc-base', __FILE__)

load(File.expand_path('../bin/mdes-console', __FILE__))
